import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Provider } from "./themeProvider"
// import ThemeSwitch from '@/components/ThemeSwitch'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'RESTRO WEB',
  description: 'Generated by Bibek KC',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning >
      <body className="bg-gray-50 dark:bg-slate-800">
        <Provider
        >
        {children}
        </Provider>
      </body>
    </html>
  )
}
